export default {
  localizationTitle: 'Русский',
  language: 'Язык',
  title: 'Генератор паролей',
  copy: 'Копировать',
  copied: 'Скопировано',
  error: 'Ошибка',
  passwordType: {
    simple: 'Обычный',
    group: 'Группами',
  },
  passwordLength: 'Длина',
  groupsCount: 'Кол-во групп',
  groupLength: 'Длина группы',
  separator: 'Разделитель',
  symbolsSequencesTooltip: {
    numbers: 'Числа',
    uppercaseLatin: 'Заглавная латиница',
    lowercaseLatin: 'Прописная латиница',
    separators: 'Разделители',
    specials: 'Спец символы',
  },
  settings: 'Настройки',
  theme: 'Тема',
  themeValues: {
    system: 'Системная',
    dark: 'Темная',
    light: 'Светлая',
  },
};
